version: '3.8'
name: bus
services:
  web:
    build:
      context: ./flask
    ports:
      - 3000:3000
    volumes:
      - ./flask:/workspace/flask
    networks:
      - proxy
      - database
    container_name: web
   
  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - web
    volumes:
      - ./flask:/workspace/flask
      - /var/log/bus_web:/var/log/nginx
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=bus.taipeilife.site
      - LETSENCRYPT_HOST=bus.taipeilife.site
    container_name: proxied-bus

networks:
  proxy:
    external: true
    name: self-nginx-proxy
  
  database:
    external: true
    name: self-mysql
