version: '3.8'
name: nginx-proxy-compose 
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
    container_name: nginx-proxy
    networks:
      - proxy
  
  nginx-proxy-letsencrypt:
    image: nginxproxy/acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=krunch522@gmail.com
    container_name: letsencrypt
    networks:
      - proxy

volumes:
  certs:
  html:
  vhost:
  acme:

networks:
  proxy:
    name: self-nginx-proxy
